---
# Tache d'installation Apache
- name: Installation Apache MSI
  hosts: windows

  tasks:
    - name: Creation du repertoire Apache
      win_command: cmd.exe /e:ON mkdir -p c:\apache 

    - name: Copie Apache
      win_copy:
        src: /home/ansible/git/Factory/install/apache/
        dest: C:\apache\
        force: yes


    - name: Install MSI
      win_package:
        path: C:\apache\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present
