---
# Tache d'installation Apache
- name: Installation Apache MSI
  hosts: windows

  tasks:
    - name: Creation du repertoire Apache
      win_command: cmd.exe /e:ON mkdir -p c:\apache 

    - name: Copie Apache
      win_copy:
        src: /home/ansible/git/Factory/install/apache/
        dest: C:\apache\
        force: yes


    - name: Install MSI
      win_package:
        path: C:\apache\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present

    - name: configuration apache
      win_copy:
        src: c:\apache\httpd.conf
        dest: c:\Program Files (x86)\Apache Software Foundation\Apache2.2\conf\
        remote_src: yes
        force: yes

    - name: installation service Apache
      win_command: httpd.exe -k install -n "apache"
      ignore_errors: yes
      args:
         chdir: c:\Program Files (x86)\Apache Software Foundation\Apache2.2\Bin\

    - name: lancement service apache
      win_command: powershell NET START apache
      ignore_errors: yes

