---
# Tache de mise en place de wordpress
#- name: Installation wordpress
# hosts: windows

# tasks:
    - name: Creation du repertoire WP
      win_command: cmd.exe /e:ON mkdir -p c:\wp

    - name: Copie Wordpress
      win_copy:
        src: /home/ansible/git/Factory/roles/wordpress/files/
        dest: C:\wp\
        force: yes


    - name: Decompression zip
      win_command: powershell.exe Expand-Archive -Force c:\wp\wordpress-5.6-fr_FR.zip c:\

    - name: Mise a jour httpd.conf
      win_copy:
        src: C:\wp\httpd.conf
        dest: C:\Apache24\conf
        remote_src: yes
        force: yes
    
    - name: Arret service Apache
      win_command: powershell NET STOP Apache

    - name: Demarrage service Apache
      win_command: powershell NET START Apache

