---
# Tache installation python
#- name: Installation python
# hosts: windows

# tasks:
    - name: Creation du repertoire python
      win_command: cmd.exe /e:ON mkdir -p c:\python

    - name: Copie python et module
      win_copy:
        src: /home/ansible/git/Factory/roles/python/files/
        dest: C:\python\
        force: yes


    - name: installation exe
      raw: 'c:\python\python-3.9.1-amd64.exe /quiet /passive InstttallAllUsers=1 PrependPath=1 Include_test=1 Include_pip=1 Include_lib=1 Include_dev=1 Include_tools=1'

    - name: installation pyad
      raw: 'py -m pip install pyad'

    - name: installation pywin32
      raw: 'py -m pip install pypiwin32'

    - name: lancement module création répertoire
      win_command: py c:\python\modcreadoss.py
      args:
        chdir: c:\

