---
# Tache d'installation Apache
#- name: Installation MariaDB MSI
# hosts: windows

# tasks:
    - name: Creation du repertoire MariaDB
      win_command: cmd.exe /e:ON mkdir -p c:\mariadb 

    - name: Copie MariaDB
      win_copy:
        src: /home/ansible/git/Factory/install/mariadb/
        dest: C:\mariadb\
        force: yes


    - name: Install MSI
      win_package:
        path: C:\mariadb\mariadb-10.5.4-winx64.msi
        state: present

    - name: creation base de donnees
      mysql_db:
        name: distribution
        state: present

    - name: creation admin de database
      mysql_user:
        name: admin
        password: admin
        priv; admin.*:ALL
        state: present

